name: Django CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t buildcv .

      - name: Run migrations
        run: docker run --rm buildcv python manage.py migrate

      - name: Run tests
        run: docker run --rm buildcv python manage.py test

      - name: Django system check
        run: docker run --rm buildcv python manage.py check
